name: Deploy Preevy environment
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  id-token: write
  contents: read
  pull-requests: write
concurrency: preevy-${{ github.event.number }}
jobs:
  deploy:
    timeout-minutes: 15

    environment:
      name: pr-${{ github.event.number }}
      url: ${{ fromJson(steps.preevy_up.outputs.urls-map).frontend[3000] }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: gcloud_auth
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: access_token
          credentials_json: '${{ secrets.PREEVY_SA_KEY }}'

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: me-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.gcloud_auth.outputs.access_token }}

      # required by imjasonh/gke-auth
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18

      # this is a lot faster than installing gcloud and gke-gcloud-auth-plugin
      - uses: imjasonh/gke-auth@v0.2.0
        with:
          project: ${{ vars.GOOGLE_CLOUD_PROJECT }}
          location: ${{ vars.GOOGLE_CLOUD_KUBE_CLUSTER_LOCATION }}
          cluster: ${{ vars.GOOGLE_CLOUD_KUBE_CLUSTER_NAME }}

      - name: Configure buildx
        id: buildx_setup
        uses: docker/setup-buildx-action@v3
        with:
          driver: kubernetes

      - name: Deploy Preevy environment
        id: preevy_up
        uses: livecycle/preevy-up-action@v2.4.0
        with:
          install: 'gh-release'
          profile-url: ${{ vars.PREEVY_PROFILE_URL }}
          args: "--driver kube-pod --registry '${{ vars.GOOGLE_CLOUD_REGISTRY }}' --builder '${{ steps.buildx_setup.outputs.name }}' --kube-pod-template=preevy-template.yaml.njk"
        env:
          GITHUB_TOKEN: ${{ github.token }}
